name: attributable
version: 0.1.2
description: >
  Allows to create getters and setters for attributes
  on a model, as well as callbacks for them.

author: Roman Snitko <roman.snitko@gmail.com>
homepage: https://github.com/snitko/dart-attributable

dev_dependencies:
  test: '>=0.12.0'
